// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njjggyhqddbuzbzibbja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qamdneWhxZGRidXpiemliYmphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkxNzc2NDEsImV4cCI6MjA4NDc1MzY0MX0.pqjJTcZDJjDEhinpSjrGUYdeO3dmIDx6HFEI2ub-was";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});